# Generated by Django 5.1.3 on 2024-11-21 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventasapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productos',
            name='fecha_elaboracion',
            field=models.DateField(blank=True),
        ),
    ]
