# Generated by Django 5.1.3 on 2024-11-21 15:19

import django.core.validators
import ventasapp.validadores
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventasapp', '0002_alter_clientes_cedula_alter_clientes_nombre_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientes',
            name='apellido',
            field=models.CharField(max_length=50, validators=[ventasapp.validadores.Validacion_letras]),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='direccion',
            field=models.TextField(validators=[django.core.validators.RegexValidator(message='el campo solo debe contener letras y espacios', regex='^[a-zA-Z0-9,-ó\\s]+$')]),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='email',
            field=models.EmailField(max_length=254, unique=True, validators=[django.core.validators.RegexValidator(message='el campo solo debe contener letras y espacios', regex='^[a-zA-Z0-9,-ó\\s]+$')]),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='nombre',
            field=models.CharField(max_length=50, validators=[ventasapp.validadores.Validacion_letras], verbose_name='Nombre del cliente : '),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='telefono',
            field=models.CharField(max_length=10, validators=[ventasapp.validadores.validacion_numeros]),
        ),
        migrations.AlterField(
            model_name='empleados',
            name='apellido',
            field=models.CharField(max_length=50, validators=[ventasapp.validadores.Validacion_letras]),
        ),
        migrations.AlterField(
            model_name='empleados',
            name='cedula',
            field=models.CharField(max_length=10, primary_key=True, serialize=False, unique=True, validators=[ventasapp.validadores.validacion_numeros], verbose_name='Cedula del Empleado :'),
        ),
        migrations.AlterField(
            model_name='empleados',
            name='direccion',
            field=models.TextField(validators=[django.core.validators.RegexValidator(message='el campo solo debe contener letras y espacios', regex='^[a-zA-Z0-9,-ó\\s]+$')]),
        ),
        migrations.AlterField(
            model_name='empleados',
            name='email',
            field=models.EmailField(max_length=254, unique=True, validators=[django.core.validators.RegexValidator(message='el campo solo debe contener letras y espacios', regex='^[a-zA-Z0-9,-ó\\s]+$')]),
        ),
        migrations.AlterField(
            model_name='empleados',
            name='nombre',
            field=models.CharField(max_length=50, validators=[ventasapp.validadores.Validacion_letras], verbose_name='Nombre del Empleado : '),
        ),
        migrations.AlterField(
            model_name='empleados',
            name='telefono',
            field=models.CharField(max_length=10, validators=[ventasapp.validadores.validacion_numeros]),
        ),
        migrations.AlterField(
            model_name='empresas',
            name='direccion',
            field=models.TextField(validators=[django.core.validators.RegexValidator(message='el campo solo debe contener letras y espacios', regex='^[a-zA-Z0-9,-ó\\s]+$')]),
        ),
        migrations.AlterField(
            model_name='empresas',
            name='email',
            field=models.EmailField(max_length=254, unique=True, validators=[django.core.validators.RegexValidator(message='el campo solo debe contener letras y espacios', regex='^[a-zA-Z0-9,-ó\\s]+$')]),
        ),
        migrations.AlterField(
            model_name='empresas',
            name='nombre',
            field=models.CharField(max_length=50, validators=[ventasapp.validadores.Validacion_letras], verbose_name='Nombre de la empresa : '),
        ),
        migrations.AlterField(
            model_name='empresas',
            name='ruc',
            field=models.CharField(max_length=13, primary_key=True, serialize=False, unique=True, validators=[ventasapp.validadores.validacion_numeros]),
        ),
        migrations.AlterField(
            model_name='empresas',
            name='telefono',
            field=models.CharField(max_length=10, validators=[ventasapp.validadores.validacion_numeros]),
        ),
        migrations.AlterField(
            model_name='productos',
            name='cantidad_stock',
            field=models.IntegerField(validators=[ventasapp.validadores.validacion_numeros], verbose_name='Cantidad en stock : '),
        ),
        migrations.AlterField(
            model_name='productos',
            name='caracteristicas_categoria',
            field=models.CharField(choices=[('Bebidas', 'Bebidas'), ('Comidas', 'Comidas'), ('Limpieza', 'Limpieza'), ('Ropa', 'Ropa'), ('Varios', 'Varios')], max_length=100, validators=[django.core.validators.RegexValidator(message='el campo solo debe contener letras y espacios', regex='^[a-zA-Z0-9,-ó\\s]+$')]),
        ),
        migrations.AlterField(
            model_name='productos',
            name='codigo',
            field=models.CharField(max_length=10, primary_key=True, serialize=False, unique=True, validators=[ventasapp.validadores.validacion_numeros]),
        ),
        migrations.AlterField(
            model_name='productos',
            name='fecha_vencimiento',
            field=models.DateField(default='2024-01-01'),
        ),
        migrations.AlterField(
            model_name='productos',
            name='marca',
            field=models.CharField(max_length=50, unique=True, validators=[ventasapp.validadores.Validacion_letras]),
        ),
        migrations.AlterField(
            model_name='productos',
            name='nombre',
            field=models.CharField(max_length=50, validators=[ventasapp.validadores.Validacion_letras], verbose_name=' Nombre del producto : '),
        ),
        migrations.AlterField(
            model_name='productos',
            name='precio',
            field=models.DecimalField(decimal_places=2, help_text='ingresa valores con decimales', max_digits=10, validators=[ventasapp.validadores.validacion_numeros], verbose_name='Precio del producto : '),
        ),
        migrations.AlterField(
            model_name='proveedores',
            name='apellido',
            field=models.CharField(max_length=50, validators=[ventasapp.validadores.Validacion_letras]),
        ),
        migrations.AlterField(
            model_name='proveedores',
            name='email',
            field=models.EmailField(max_length=254, unique=True, validators=[django.core.validators.RegexValidator(message='el campo solo debe contener letras y espacios', regex='^[a-zA-Z0-9,-ó\\s]+$')]),
        ),
        migrations.AlterField(
            model_name='proveedores',
            name='nombre',
            field=models.CharField(max_length=50, validators=[ventasapp.validadores.Validacion_letras], verbose_name='Nombre del proveedor : '),
        ),
        migrations.AlterField(
            model_name='proveedores',
            name='telefono',
            field=models.CharField(max_length=10, validators=[ventasapp.validadores.validacion_numeros]),
        ),
    ]
